name: n2euro
favicon: null
layout_spectrum: 0.821587250335142
typography_spectrum: 0.8017687671817839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7495775297284126
  lightness: 0.16647748951800168
  saturation: 0.1772416401654482
  rhythmicContrast: 0.5854645573999733
purpose: []
